### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/Users/tony/Development/Collectr/contain...

### ISSUE THREAD

**Issue by gamebox** [booms8/gulp-task-launcher#1]
[Enter steps to reproduce below:]
1. Toggle gulp-task-launcher

**Atom Version**: 1.5.3
**System**: Mac OS X 10.10.3
**Thrown From**: [gulp-task-launcher](https://github.com/booms8/gulp-task-launcher) package, v1.4.5
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/tony/Development/Collectr/containers/dashing/dashing-rc.yaml.j2'

```
At fs.js:854

Error: ENOENT: no such file or directory, stat '/Users/tony/Development/Collectr/containers/dashing/dashing-rc.yaml.j2'
    at Error (native)
    at fs.statSync (fs.js:854:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:225:16)
    at gulpTaskLauncherView.module.exports.gulpTaskLauncherView.getGulpCwd (/Users/tony/.atom/packages/gulp-task-launcher/lib/gulp-task-launcher-view.coffee:80:23)
    at gulpTaskLauncherView.module.exports.gulpTaskLauncherView.getGulpCwd (/Users/tony/.atom/packages/gulp-task-launcher/lib/gulp-task-launcher-view.coffee:84:25)
    at gulpTaskLauncherView.module.exports.gulpTaskLauncherView.getGulpCwd (/Users/tony/.atom/packages/gulp-task-launcher/lib/gulp-task-launcher-view.coffee:84:25)
    at gulpTaskLauncherView.module.exports.gulpTaskLauncherView.getGulpTasks (/Users/tony/.atom/packages/gulp-task-launcher/lib/gulp-task-launcher-view.coffee:94:28)
    at gulpTaskLauncherView.module.exports.gulpTaskLauncherView.toggle (/Users/tony/.atom/packages/gulp-task-launcher/lib/gulp-task-launcher-view.coffee:57:21)
    at atom-workspace.atom.commands.add.gulp-task-launcher:toggle (/Users/tony/.atom/packages/gulp-task-launcher/lib/gulp-task-launcher-view.coffee:20:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:02.7.0 gulp-task-launcher:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "gulp-task-launcher": {}
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
color-picker, v2.1.1
file-icons, v1.6.14
gulp-task-launcher, v1.4.5
language-protobuf, v0.5.0
language-scala, v1.1.6
minimap, v4.19.0
minimap-git-diff, v4.1.8
pretty-json, v0.4.1
set-syntax, v0.3.0

# Dev
No dev packages
```

**Comment by booms8** [comment]
Thanks for alerting me. I assume that file actually does exist?

**Comment by booms8** [comment]
I think this was due to an issue with fs; I've pushed a fix.

**Comment by gamebox** [comment]
Nice, I'll try it out when it's live

**Comment by booms8** [comment]
How's it working?
